### ISSUE TITLE
Question concerning wallpaper

### ISSUE THREAD

**Issue by csteinforth** [fhdk/manjaro-wallpapers-by-lunix#1]
Please don't get me wrong, but I have to be frank on this. I skipped through the manjaro wallpapers and I think that the manjaro-wallpapers-by-lunix/manjaro/manjaro017.jpg has a strong resemblance with a swastika. Do you think it is possible to remove this?

**Comment by fhdk** [comment]
I don't agree - it is a Manjaro Logo - quite obvious.
